<a href="https://colab.research.google.com/github/zahed3795/AI_QA_Testing/blob/main/00_PyTorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
## PyTorch Fundamentals


In [3]:
print("Hello!!!!\nI am excited to learn PyTorch")

import  pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import  torch
print(torch.__version__)

## Introduction to Tensors



Hello!!!!
I am excited to learn PyTorch
2.5.1+cu124


PyTorch tensors are created using 'torch.Tensor()' =

In [4]:
# Scalar
import   torch
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
#Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
scalar.ndim
# Get tensor back as Python int
scalar.item()

7

In [ ]:
vector.ndim


1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
MATRIX = torch.tensor([[7,8],
              [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [18]:
# Tensor
TENSOR = torch.tensor([[[[1,2,4],
                        [3,5,6],
                        [8,9,0],
                        [1,2,3]]]])

TENSOR

tensor([[[[1, 2, 4],
          [3, 5, 6],
          [8, 9, 0],
          [1, 2, 3]]]])

In [11]:
TENSOR.ndim

4

In [15]:
TENSOR.shape

#DIMENSION
#dim=0
#dim=1
#dim=2

torch.Size([1, 1, 4, 3])

In [ ]:
### Random Tensors

### Random Tensors

Why random Tensor?

Random Tensor are important becasue the way many neural networks learn is that they start with tensor full of random numbers and then adjust those random numbers to better represent the data. 'Start with random numbers -> look at data -> Update random numbers -> look at data ->Update the random number'


In [19]:
random_tensor = torch.rand(3,4)
random_tensor


tensor([[0.9717, 0.0847, 0.9895, 0.5310],
        [0.7060, 0.3387, 0.4556, 0.1982],
        [0.5442, 0.9117, 0.0931, 0.8746]])

In [20]:
random_tensor.ndim


2

In [22]:
random_image_size_tensor = torch.rand(size=(3795,3795,1)) # Height, Width, Color channel
random_image_size_tensor.shape , random_image_size_tensor.ndim

(torch.Size([3795, 3795, 1]), 3)